SELECT B.USER_ID USER_ID, B.NICKNAME NICKNAME,
       CONCAT(B.CITY, CONCAT(' ', CONCAT(B.STREET_ADDRESS1, CONCAT(' ', B.STREET_ADDRESS2)))) 전체주소,
       CONCAT(SUBSTRING(B.TLNO, 1, 3), CONCAT('-', CONCAT(SUBSTRING(B.TLNO, 4, 4), CONCAT('-', SUBSTRING(B.TLNO, 8, 4))))) 전화번호
FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
GROUP BY A.WRITER_ID
HAVING COUNT(BOARD_ID) >= 3
ORDER BY B.USER_ID DESC