# SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, SUBSTRING(B.CREATED_DATE, 1, 10) AS CREATED_DATE
# FROM USED_GOODS_BOARD A INNER JOIN USED_GOODS_REPLY B
# ON A.BOARD_ID = B.BOARD_ID
# WHERE YEAR(B.CREATED_DATE)='2022' AND MONTH(B.CREATED_DATE)='10'
# ORDER BY B.CREATED_DATE, A.TITLE

SELECT BOARD.TITLE, BOARD.BOARD_ID, REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, SUBSTRING(REPLY.CREATED_DATE, 1, 10)
FROM USED_GOODS_BOARD BOARD INNER JOIN USED_GOODS_REPLY REPLY
ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE YEAR(BOARD.CREATED_DATE) = '2022' AND MONTH(BOARD.CREATED_DATE) = '10'
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE

# DAYNAME => 요일
# DAYOFMONTH => 일
# WEEKDAY => 주
# MONTH => 월
# YEAR => 년