SELECT BOARD.TITLE, BOARD.BOARD_ID, REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, SUBSTRING(REPLY.CREATED_DATE, 1, 10)
FROM USED_GOODS_BOARD BOARD INNER JOIN USED_GOODS_REPLY REPLY
ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE YEAR(BOARD.CREATED_DATE) = '2022' AND MONTH(BOARD.CREATED_DATE) = '10'
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE

# DAYNAME => 요일
# DAYOFMONTH => 일
# WEEKDAY => 주
# MONTH => 월
# YEAR => 년