SELECT DEP.DEPT_ID AS DEPT_ID, DEP.DEPT_NAME_EN AS DEPT_NAME_EN, ROUND(AVG(EMP.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT DEP JOIN HR_EMPLOYEES EMP
ON DEP.DEPT_ID = EMP.DEPT_ID
GROUP BY DEPT_ID
ORDER BY AVG_SAL DESC